###################################################################################
###Effect of antibiotic duration on resistance carriage in hospitalised patients###
################## Plot partial correlation coefficient ###########################
###################################################################################

library(pse)
library(ggplot2)
library(ggpubr)

##### partial correlation coefficient measures how strong are the linear associations between the result 
# and each input parameter, after removing the linear effect of the other parameters. 
# (CI generated by bootstrapping)

plotprcc<-function(LHS.run){
  
  prcc=LHS.run$prcc[[21]]$PRCC
  x.samples=LHS.run[['data']]
  y.output=LHS.run$res[,21,1]
  dat= cbind.data.frame(x.samples, y.output)
  prcc<-prcc[order(prcc$original, decreasing = TRUE),]
  prcc$hi_lo<-rep(NA, nrow(prcc))
  prcc$hi_lo[which(prcc$`min. c.i.`>0 & prcc$`max. c.i.`>0) ]='Above'
  prcc$hi_lo[which(prcc$`max. c.i.`<0 & prcc$`min. c.i.`<0) ]='Below'
  prcc$hi_lo[is.na(prcc$hi_lo)]='None'
  prcc$hi_lo=as.factor(prcc$hi_lo)
  rownames.prcc<-factor(as.factor(rownames(prcc)), levels = rownames(prcc))
  Colors <- setNames(c('#eb5160',"#388697",'grey'), c('Above', 'Below','None'))
  
  plot=ggplot(data=prcc, mapping = aes(x = rownames.prcc, y = original)) +
    geom_hline(yintercept=0, color = "azure2")+
    geom_point()+
    geom_errorbar(aes(ymin=`min. c.i.`, ymax=`max. c.i.`, color=hi_lo), width=0.3)+
    scale_color_manual("hi_lo", breaks=c(1,2,3,4),values=Colors)+
    geom_point(aes(fill=hi_lo),size=2, shape=21)+
    scale_fill_manual("hi_lo",breaks=c(1,2,3,4),values=Colors)+
    scale_x_discrete(rownames.prcc)+
    scale_y_continuous(limits = c(-1,1))+
    labs(y="Partial Ranking Correlation Coefficients",
         x="")+
    theme(axis.text.x = element_text(angle = 90, hjust = 1),
          panel.background = element_blank())
  
  return(plot)
}


